prosopo_procaptcha_settings:
  path: /prosopoprocaptcha/configuration
  methods: [ GET, POST ]
  defaults:
    _controller: 'Io\Prosopo\Procaptcha\Settings\SettingsController::index'
    # Needed to work with the tab system
    _legacy_controller: ProsopoProcaptchaSettings
    _legacy_link: ProsopoProcaptchaSettings
