services:
  _defaults:
    public: true

  Io\Prosopo\Procaptcha\Settings\SettingsController:
    arguments:
      - '@prestashop.module.prosopoprocaptcha.form.settings_data_handler'
      - '@prestashop.module.prosopoprocaptcha.form.settings_configuration'
      - '@prestashop.module.prosopoprocaptcha.widget'
      - '@prestashop.module.prosopoprocaptcha.views'

  prestashop.module.prosopoprocaptcha.form.type.settings_form_type:
    class: 'Io\Prosopo\Procaptcha\Settings\SettingsFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.prosopoprocaptcha.form.settings_configuration:
    class: 'Io\Prosopo\Procaptcha\Settings\SettingsConfiguration'
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  prestashop.module.prosopoprocaptcha.form.settings_data_provider:
    class: 'Io\Prosopo\Procaptcha\Settings\SettingsDataProvider'
    arguments:
      - '@prestashop.module.prosopoprocaptcha.form.settings_configuration'

  prestashop.module.prosopoprocaptcha.form.settings_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.prosopoprocaptcha.form.settings_data_provider'
      - 'Io\Prosopo\Procaptcha\Settings\SettingsFormType'
      - 'ProcaptchaSettingsForm'

  prestashop.module.prosopoprocaptcha.widget:
    class: 'Io\Prosopo\Procaptcha\Widget'
    arguments:
      - 'widget'
      - '@prestashop.module.prosopoprocaptcha.views'
      - '@prestashop.module.prosopoprocaptcha.form.settings_configuration'

  prestashop.module.prosopoprocaptcha.views:
    class: 'Io\Prosopo\Procaptcha\Views'
    arguments:
      - '@@Modules/prosopoprocaptcha/views'
      - '@twig'
