<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2uvFURI\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2uvFURI/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container2uvFURI.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container2uvFURI\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container2uvFURI\appAppKernelProdContainer([
    'container.build_hash' => '2uvFURI',
    'container.build_id' => 'e05f947e',
    'container.build_time' => 1750072896,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2uvFURI');
